### ISSUE TITLE
An Error in PhylotaR

### ISSUE THREAD

**Issue by ZQ1126** [ropensci/phylotaR#38]
Hi Dom,

I am now using phylotaR for processed the data in Blats+. During the processing of PhylotaR, it shows an error may need you help to solve. Below were the script I used and the Error it shows.
The Script I Used:
> library(phylotaR)
> wd<-'e:/Institute_Of_Bontany/WorldTree/TracheophytaTest'
> ncbi_dr<-'d:/blast/blast-2.7.1+/bin/'
> txid<-58023
>  setup(wd=wd,txid=txid,ncbi_dr=ncbi_dr,v=TRUE)
-------------------------------------------------
phylotaR: Implementation of PhyLoTa in R [v1.0.0]
-------------------------------------------------
Checking for valid NCBI BLAST+ Tools ...
Found: [d:/blast/blast-2.7.1+/bin//makeblastdb]
Found: [d:/blast/blast-2.7.1+/bin//blastn]
Setting up pipeline with the following parameters:
. blstn      [d:/blast/blast-2.7.1+/bin//blastn]
. btchsz     [100]
. date       [2018-10-22]
. mdlthrs    [3000]
. mkblstdb   [d:/blast/blast-2.7.1+/bin//makeblastdb]
. mncvrg     [51]
. mnsql      [250]
. mxevl      [1e-10]
. mxnds      [1e+05]
. mxrtry     [100]
. mxsql      [2000]
. mxsqs      [50000]
. ncps       [1]
. txid       [58023]
. v          [TRUE]
. wd         [e:/Institute_Of_Bontany/WorldTree/TracheophytaTest]
-------------------------------------------------
> run(wd=wd)

The Error it shows:
Generating taxonomic dictionary ...
Unexpected Error in FUN(X[[i]], ...) : Unable to get "PRNT" slot from object without slot basic category ("NULL")

Occurred [2018-10-23 09:06:12]
Contact package maintainer for help.
Error in stages_run(wd = wd, frm = 1, to = nstages, stgs_msg = stgs_msg) : 
  Unexpected Error in FUN(X[[i]], ...) : Unable to get "PRNT" slot from object without slot basic category ("NULL")

Best Wishes,
Qiang

**Comment by DomBennett** [comment]
Hi

This is likely due to an error in a taxonomic record downloaded from NCBI. It should be fixable by running the download step again. I've made some updates to phylotaR to better capture these kinds of errors.

Try:

```r
# install newer version of phylotaR
devtools::install_github('ropensci/phylotaR')
```

```r
# restart your pipeline
library(phylotaR)
wd <- 'e:/Institute_Of_Bontany/WorldTree/TracheophytaTest'
restart(wd = wd)
```

If you get a warning, try halting the pipeline (use Esc or ctrl+c) and restarting again.

If you get an error, ping me here again.

These issues are due to the occasional malformed record that is retrieved from NCBI. Re-downloading again often fixes the issue. I am working on a more elegant solution.

Thanks for using phylotaR!

Dom

P.S. @Cactusolo the above should work for you too.

**Comment by Cactusolo** [comment]
@DomBennett Thank you so much! It works now!

Miao

**Comment by ZQ1126** [comment]
Thanks for your kindly help, it works again. @DomBennett
